version: '3'

services:
  web-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: backend-development
    ports:
      - '8081:8080'
    environment:
      - HUSKY=0
