services:
  backend-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: backend-development
    ports:
      - '8081:8080'
    env_file:
      - ../../.env.development
