services:
  backend-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: backend-production
    ports:
      - '80:80'
    env_file:
      - ../../.env
