services:
  backend-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: backend-staging
    ports:
      - '8082:8080'
    env_file:
      - ../../.env.staging
